# Generated by Django 5.1.1 on 2024-09-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='given_name',
        ),
    ]
